### PR TITLE
Use Normal string for QOTD and add Edit QOTD button and modal

### PR DESCRIPTION
**Pull request by HoodieRocks**
This pull request simply changes how the bot prints out automated QOTD messages so that they show up in the forum post short description. In addition, it also adds an edit button to edit the message after the bot has sent it (in case of spelling mistakes)

### CODE REVIEW

**Comment by PuckiSilver** [comment]
IMG_9141
Are you sure this change still does the intended thing? Because to me it’s checking if a string is not the type string, which will always be true.

IMG_9142
After this, the edited message will be the new question **without** the QOTD ping or who suggested it - imo that looks weird if edited questions just have a completely different format.
And if it can’t send the message - the content gets set to the error message? Should probably never happen but that does sound unintuitive to me.

**Comment by FIyrr** [comment]
yea i don't see when `message.content` would ever not be a string

**Comment by HoodieRocks** [comment]
I'm just using what was provided to me, if you want me to remove the check I can, but either way it's been proven to work with the check in place or not

**Comment by PuckiSilver** [comment]
No that check is there because in the library - it can also not be a string (think image or embed) - that’s why the check is necessary.

My proposed solution is keeping it the way it was, with the type(…) != str since that checks if the type is string. The new way after your changes, is checks if "String" is equals to the class str, which it will never be since it's not a class, rather an object of that class.

**Review by Silabear — COMMENTED** [review]
I don't like there being a publicly visible button for this very specific use case. There shouldn't be spelling mistakes anyway because we would theoretically have days to check them before they are sent

**Comment by HoodieRocks** [comment]
The scope of this PR has been reduced to the point where it can probably be a commit

**Pull request closed without merging**
