### PR TITLE
auto deletion for arabic messages

### PR DESCRIPTION
**Pull request by HeDeAnTheonlyone**

### CODE REVIEW

**Comment by Sleet827** [comment]
You're evil /j

**Comment by Sleet827** [comment]
Actually, what I suggest, considering you already have a system to detect arabic messages, why don't you go an extra mile and translate them?

**Comment by FIyrr** [comment]
Because we'd need to pay for an api
Also only translating arabic messages would be weirdly specific

**Comment by Sleet827** [comment]
> Because we'd need to pay for an api Also only translating arabic messages would be weirdly specific

1. The Python module `deep_translator` has multiple translators, and a few of them like Google Translate don't need an API [deep_translator](https://pypi.org/project/deep-translator/#google-translate-1)
2. We can just set the `source` to `"auto"` in any message that is detected to have non-english characters, and it will either:
        1. Create a webhook just like the syntax highlighter does, the only drawback is that it won't work on languages using latin script all the time.
        2. We could just _not_ block Arabic messages at all, and make the translator an App which can be used on a message just like ~~skibidi~~ redirect.

**Comment by HoodieRocks** [comment]
Automod has been configured to replace this. Closed

**Pull request closed without merging**
